### ISSUE TITLE
三级城市点击就闪退了，日志如下，估计是字符串数据格式对不上，解析异常了，但是没看到在哪

### ISSUE THREAD

**Issue by luoqiang108** [Jlanglang/TreeRecyclerView#14]
2019-05-07 17:23:29.023 30128-30200/com.baozi.treerecyclerview E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.baozi.treerecyclerview, PID: 30128
    com.alibaba.fastjson.JSONException: error parse set
        at com.alibaba.fastjson.parser.JSONLexerBase.scanSet(JSONLexerBase.java:2794)
        at com.alibaba.fastjson.parser.JSONLexerBase.nextToken(JSONLexerBase.java:165)
        at com.alibaba.fastjson.parser.JSONLexerBase.nextToken(JSONLexerBase.java:359)
        at com.alibaba.fastjson.parser.DefaultJSONParser.<init>(DefaultJSONParser.java:179)
        at com.alibaba.fastjson.parser.DefaultJSONParser.<init>(DefaultJSONParser.java:154)
        at com.alibaba.fastjson.JSON.parseArray(JSON.java:347)
        at com.baozi.demo.activity.CityListActivity$1.run(CityListActivity.java:42)

**Comment by Jlanglang** [comment]
找到原因了,已经修复.因为string里的资源String太长了.打包被替换成一个"STRING_TOO_LARGE".
已经换了一种方式读取城市数据了
